version: '3'
services:
  db:
    image: mysql
    container_name: edo
    volumes:
      - /tmp/db:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: .env

  web:
    build:
      context: .
      args:
        working_dir: /www
    image: floss-pa/website:latest
    container_name: meiji
    command: rails s -p 3000 -b '0.0.0.0'
    entrypoint:
      - bundle
      - exec
    volumes:
      - .:/www
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - RAILS_SERVE_STATIC_FILES=false
      - RAKE_ENV=development
    depends_on:
      - db
